"""add file and callback columns to jobs

Revision ID: b9a98de5845a
Revises: 307e8bf748b2
Create Date: 2026-07-04 19:57:07.305274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9a98de5845a'
down_revision: Union[str, Sequence[str], None] = '307e8bf748b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('translation_jobs', sa.Column('file_name', sa.String(length=255), nullable=True))
    op.add_column('translation_jobs', sa.Column('file_format', sa.String(length=16), nullable=True))
    op.add_column('translation_jobs', sa.Column('skeleton_json', sa.Text(), nullable=True))
    op.add_column('translation_jobs', sa.Column('callback_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('translation_jobs', 'callback_url')
    op.drop_column('translation_jobs', 'skeleton_json')
    op.drop_column('translation_jobs', 'file_format')
    op.drop_column('translation_jobs', 'file_name')
    # ### end Alembic commands ###
